select substr(regexp_substr(notes,"Category FLeet List"),10)as Category,
substr(regexp_substr(notes,"SECTION A: [A-Z]+[A-Z ]*"),11)  as SectionA,
substr(regexp_substr(notes,"NAME: [A-Z][a-z][^\|]*"),6)  as Name
substr(regexp_substr(notes,"TYPE:[^\|]*"),6)  as Type,
substr(regexp_substr(notes,"YEAR BUILT:[^\|]*"),13)  as YearBuilt,
substr(regexp_substr(notes,"BUILDER:[^\|]*"),9)   as Builder,
substr(regexp_substr(notes,"COUNTRY WHERE BUILT:[^\|]*"),22)  as BuildCountry,
substr(regexp_substr(notes,"LBP:[^\|]*"),4)  as Lbp,
substr(regexp_substr(notes,"BEAM:[^\|]*"),6)  as Beam,
substr(regexp_substr(notes,"MOULDED DEPTH:[^\|]*"),15)  as MouldedDepth,
substr(regexp_substr(notes,"GROSS TONNAGE:[^\|]*"),16)  as GrossTonnage,
substr(regexp_substr(notes,"NET TONNAGE:[^\|]*"),14)  as Beam,
substr(regexp_substr(notes,"SECTION B:[^\|]*"),12)  as SectionB,
substr(regexp_substr(notes,"CSL OWNERSHIP DATES:[^\|]*"),1)  as OwnerShipDate,
substr(regexp_substr(notes,"FROM:[^\|]*"),6)  as 'DateFrom',
substr(regexp_substr(notes,"TO:[^\|]*"),4)  as 'DateTo',
substr(regexp_substr(notes,"VESSEL'S OTHER NAME:[^\|]*"),21)  as 'vesselOtherName',
substr(regexp_substr(notes,"CHRONOLOGY:[^\|]*"),1)  as chronology,
substr(regexp_substr(notes,"(?<=OWNERSHIP\/COMMENTS)(.*)(?=SHIPYARD LOCATION)"),1)  as 'Comments',
substr(regexp_substr(notes,"SHIPYARD LOCATION:[^\|]*"),19)  as ShipyardLocation,
substr(regexp_substr(notes,"HULL NUMBER:[^\|]*"),14)  as HullNumber,
substr(regexp_substr(notes,"DATE OF LAUNCH:[^\|]*"),17)  as dateOfLaunch,
substr(regexp_substr(notes,"DATE OF DELIVERY:[^\|]*"),19)  as dateOfDelivery,
substr(regexp_substr(notes,"DATE OF LAUNCH:[^\|]*"),17)  as dateOfLaunch,
substr(regexp_substr(notes,"HULL:[^\|]*"),5)  as hullType,
substr(regexp_substr(notes,"SUPERSTRUCTURE:[^\|]*"),17)  as superstructure,
substr(regexp_substr(notes,"SECTION E:[^\|]*"),12)  as sectionE,
substr(regexp_substr(notes,"ENGINE TYPE:[^\|]*"),14)  as engineType,
substr(regexp_substr(notes,"CYLINDERS:[^\|]*"),12)  as cylinders,
substr(regexp_substr(notes,"STROKE:[^\|]*"),9)  as stroke,
substr(regexp_substr(notes,"TURBINES:[^\|]*"),11)  as turbines,
substr(regexp_substr(notes,"AT.[(][^\|]*"),1)  as atRpm,
substr(regexp_substr(notes,"YEAR BUILT:[^\|]*"),13)  as yearEngineBuilt,
substr(regexp_substr(notes,"ENGINE BUILDER:[^\|]*"),17)  as engineBuilder,
substr(regexp_substr(notes,"PLACE BUILT:[^\|]*"),17)  as placeEngineBuilt,
substr(regexp_substr(notes,"NUMBER OF BOILERS:[^\|]*"),20)  as numberOfBoilers,
substr(regexp_substr(notes,"(?<=BOILERS:[^|^[0-9])(.*)(?=[^|]*SIZE:)"),7)  as engineType,
substr(regexp_substr(notes,"SIZE:[^\|]*"),7)  as engineSize,
substr(regexp_substr(notes,"BOILER BUILDER:[^\|]*"),17)  as boilerBuilder,
substr(regexp_substr(notes,"BOW THRUSTER:[^\|]*"),15)  as bowThruster,
substr(regexp_substr(notes,"STERN THRUSTER:[^\|]*"),17)  as sternThruster
from
select notes from archive.csl limit 1
