var tmp =[
{notis:'(CaOKQ)AAD4862'},
{notis:'(CaOKQ)AAD4863'},
{notis:'(CaOKQ)AAD4864'},
{notis:'(CaOKQ)AAD4865'},
{notis:'(CaOKQ)AAD4866'},
{notis:'(CaOKQ)AAD4867'},
{notis:'(CaOKQ)AAD4868'},
{notis:'(CaOKQ)AAD4869'},
{notis:'(CaOKQ)AAD4870'},
{notis:'(CaOKQ)AAD4871'},
{notis:'(CaOKQ)AAD4872'},
{notis:'(CaOKQ)AAD4873'},
{notis:'(CaOKQ)AAD4874'},
{notis:'(CaOKQ)AAD4875'},
{notis:'(CaOKQ)AAD4876'},
{notis:'(CaOKQ)AAD4877'},
{notis:'(CaOKQ)AAD4878'},
{notis:'(CaOKQ)AAD4879'},
{notis:'(CaOKQ)AAD4880'},
{notis:'(CaOKQ)AAD4881'},
]

const key='notis'
let value = tmp[5].notis
value//?
let search = '\\'+ value.substring(0,6)+'\\'+value.substring(6)
search//?

const exp = RegExp(search,'i')

const value1 = new RegExp(tmp[0].notis,'i')


var tmp2 = tmp.filter((ele) => {
  if (ele[key] != null) {
    // return ele[key].match(/\(CaOKQ\)AAD4880/i)
    return ele[key].match(exp)
  }
  else {
    return false
  }
})

tmp2//?

const carrier =[
  {type:'C1 (Bulk Canaller)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'C1 (Canal Sized Bulk Carrier)'},
  {type:'C1 (Canaller Bulk)'},
  {type:'C1 (Combination Package Fr. and Bulk)'},
  {type:'R2 (River Pass.)'},
  {type:'C1 (Canaller Bulk)'},
  {type:'C2 (Package Ft.)'},
  {type:'S2 (Sea going Pass and Frt.)'},
  {type:'U1 (Bulk Upper Laker)'},
  {type:'U1 (Bulk Carrier Upper Lakes type)'},
  {type:'S2'},
  {type:'M1'},
  {type:'C1 (Canaller Bulk)'},
  {type:'C2 (Canal Sized Package Freighter)'},
  {type:'C2 (Upper Lake Bulk Carrier then canal sized Package'},
  {type:'T1 (Harbour Service)'},
  {type:'C2 (Canal Sized Package Freight Vessel)'},
  {type:'C6 (Passenger Freight)'},
  {type:'S2 (Pass. and Ft.)'},
  {type:'M2'},
  {type:'C6 (Passenger and Freight)'},
  {type:'U1 (Upper Lake Bulk Carrier)'},
  {type:'B1 (Bulk Grain Barge)'},
  {type:'C1'},
  {type:'U1'},
  {type:'T1 (River Tug and Harbour Tug)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'C2 (Package Frieghter)'},
  {type:'C1 (Canal Sized Bulk Carrier)'},
  {type:'C1 (Canaller Bulk)'},
  {type:'C2 (Canal Sized Package Freighter)'},
  {type:'C1 (Canaller Bulk)'},
  {type:'R3 (Passenger)'},
  {type:'R3 (Passenger Registered in U.S.)'},
  {type:'R3 (Lake and River Pass. Ship)'},
  {type:'T2 (Seagoing and Lake Tug)'},
  {type:'S4 (Pass. and Freight)'},
  {type:'C6 (Passenger and Freight)'},
  {type:'C1 (Canal Bulk Carrier and Pack. Ftr.)'},
  {type:'G4 (Pass. & Ft.)'},
  {type:'C1 (Canaller Bulk)'},
  {type:'C1 (Canaller Bulk)'},
  {type:'T1 (River and Harbour Tug)'},
  {type:'T1 (River and Harbour Tug.)'},
  {type:'C1 (Canaller Bulk)'},
  {type:'G4 (Day steamer for the Tor. Niag. Run)'},
  {type:'G4 (Passenger and Freight)'},
  {type:'S1 (Pack. Frt.)'},
  {type:'G4 (Pass. & Ft.)'},
  {type:'C2 (Canal Size Package Frt.)'},
  {type:'C2 (Canal Size Pack. Ftr.)'},
  {type:'C2 (Canal Size Package Freight)'},
  {type:'C6 (Freight and Passengers)'},
  {type:'C2 (Canal Size Pack. Ftr.)'},
  {type:'C2 (Canal Size Package Frtr.)'},
  {type:'C2 (Canal Size Package Freight)'},
  {type:'C2 (Cannal Sized Package Ftr.)'},
  {type:'C4 (Canal Sized Self unloader)'},
  {type:'C1 (Small Canaller Bulk)'},
  {type:'B1 (Grain Barge for the Kingston to Montreal grain trade of the'},
  {type:'C4 (Canal sized self-unloader)'},
  {type:'U1 (Upper Lake bulk then Upper Lake package fgtr.)'},
  {type:'G4 (Pass. & Ft.)'},
  {type:'SR (T.E.)'},
  {type:'U1'},
  {type:'C1 (Bulk Carrier)'},
  {type:'T2 (Sea going and Lake Tug)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'C1 (Canal Bulk converted to Package Freighter 1911)'},
  {type:'U1 (Upper Lake Bulk)'},
  {type:'C6 (Canal Package Freight and Passengers)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'C1 (Canal Bulk)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'U1 (Upper Laker Bulk, then self-unloader)'},
  {type:'C2 (Canal Size Package Freighter)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'U1 (Upper Lake Bulk Carrier)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'U2 (then U4)'},
  {type:'S1 (with capac. to operate in the ice. Later U2.)'},
  {type:'S1 (Freight)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'S1 (Bulk Carrier)'},
  {type:'C2 (Canal Sized Pack. Frtr.)'},
  {type:'C2 (Canal Size Package Freighter)'},
  {type:'U2'},
  {type:'U2 (Upper Lake Pack. Frt.)'},
  {type:'U2'},
  {type:'U2'},
  {type:'U2'},
  {type:'U2'},
  {type:'M1'},
  {type:'C1 (Bulk Canaller later lengthened to Upper Laker Size)'},
  {type:'B1 (St. Lawrence grain barge)'},
  {type:'U1 (Upper Laker)'},
  {type:'C6 (Passenger and Package Freight)'},
  {type:'B2 (Two Barge Upper Lake Size)'},
  {type:'U1 (Upper Laker Bulk converted to self unloader 1963)'},
  {type:'C4 (Canaller Self Unloader)'},
  {type:'U1 (Upper Lake Bulk)'},
  {type:'U1 (Upper Lakes Bulker)'},
  {type:'C1 (Canaller Bulk)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'S2 (Pass. and Freight)'},
  {type:'M2'},
  {type:'C1 (Bulk Carrier)'},
  {type:'U1 (Upper Lakers Bulk)'},
  {type:'C1 (Canaller Bulk)'},
  {type:'C1 (Canal Size Bulker)'},
  {type:'P4 (Passenger and Package Freight)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'U4'},
  {type:'U1 (Upper Lakes Bulk)'},
  {type:'P4 (Passenger and Package Freight)'},
  {type:'C1 (Canaller Bulk)'},
  {type:'C1 (Timber Drogher, then Bulk Canaller)'},
  {type:'C1'},
  {type:'S2 (Pass and Freight)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'M2'},
  {type:'M2'},
  {type:'B1 (Tow Barge for St. Lawrence Grain Trade)'},
  {type:'T1 (River and Harbour Tug)'},
  {type:'C2 (Canaller, Package Ft.)'},
  {type:'S1 (Freight)'},
  {type:'C2 (Canal Size Package Ft.)'},
  {type:'C2 (Package Freighter)'},
  {type:'G4 (Passenger, Paddle Steamer)'},
  {type:'C1 (Canaller Bulk)'},
  {type:'C1 (Canaller Bulk)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'S2 (Fright and Pass.)'},
  {type:'C1 (Bulk Steam Canaller)'},
  {type:'S4 (Coaster, Pass and Freight)'},
  {type:'U1 (Upper Laker Bulk)'},
  {type:'C1 (Bulk Steam Canaller)'},
  {type:'T2 (Lake and Seagoing Tug)'},
  {type:'C2 (Canal Size Package Ft.)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'S1 (Freight)'},
  {type:'F1 (Ferry Vehicle and Pass)'},
  {type:'M2'},
  {type:'R2 (Pass. & Ft.)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'P4 (Passenger and Freight)'},
  {type:'S1 (Wood Aux Tw. Scr. 5 Masts Ship)'},
  {type:'M2'},
  {type:'S1 (Freight)'},
  {type:'T1 (River and Harbour Tug)'},
  {type:'C2 (Canal Size Package Ftr.)'},
  {type:'C6 (Passenger and Package Freight)'},
  {type:'C2 (Canal Size Package Freight)'},
  {type:'S1 (Freight as built was a twin screw 3 funnel pass. ship built'},
  {type:'U1 (Upper Laker Bulk)'},
  {type:'C2 (Package Freighter)'},
  {type:'C2 (Canal Size Pack. Ftr.)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'C1 (Canal Bulk)'},
  {type:'C2 (Package Freighter)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'C1 (Smaller than Canal Size Bulk)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'U1 (Upper Lake Bulk Carrier)'},
  {type:'U2'},
  {type:'C1 (Canaller Bulk)'},
  {type:'B1 (St. Lawrence Canal Tow barge for the Grain trade Kingston'},
  {type:'U4 (Cement)'},
  {type:'U1 (Upper Lake Bulk)'},
  {type:'U1 (then U4 (UPPER LAKES BULK rebuilt as a SELF UNLOADER 1929))'},
  {type:'C1 (Bulk Canaller)'},
  {type:'R2 (Pass Day)'},
  {type:'R3 (Passenger)'},
  {type:'U1'},
  {type:'M1'},
  {type:'M2'},
  {type:'C2 (Package Freighter)'},
  {type:'G2 (Pass and Gen. Cargo)'},
  {type:'C1 (Canaller)'},
  {type:'U1'},
  {type:'C1 (Bulk Canaller)'},
  {type:'P4 (Passenger and Freight)'},
  {type:'R4 (Pass. and Ft.)'},
  {type:'T1 (Supply Boat)'},
  {type:'C2 (Canal Package Freighter)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'U1 (small upper laker bulk)'},
  {type:'S2 (Pass. and Frt.)'},
  {type:'C1 (Canaller Bulk)'},
  {type:'C1 (Canal Size Bulk Carrier)'},
  {type:'U1 (Upper Laker, Bulk)'},
  {type:'M1 (and S1 Caribbean Class)'},
  {type:'U1 (Upper Laker, Bulk)'},
  {type:'R3 (Passenger)'},
  {type:'R3 (Passenger Ship for St. Lawrence and Sag. R. Service)'},
  {type:'R3 (Specialized Pass. Vessel for the Rapids Run)'},
  {type:'R3 (Spec. Pass. Service running rapids in Upper St. Lawrence)'},
  {type:'R3 (Spec. Passenger Vessel for the St. Lawrence Rapids)'},
  {type:'U2 (Upper Lakes Pack. Ftr.)'},
  {type:'C1 (Canal size bulk carrier)'},
  {type:'U2 (Upper Lake Pack. Ft.)'},
  {type:'R3 (Passenger Cruise Ship)'},
  {type:'M1'},
  {type:'M1'},
  {type:'T1 (River and Harour Tug)'},
  {type:'C1 (Combination Bulk and Package Freighter)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'R3 (Passenger)'},
  {type:'M1 (then M2)'},
  {type:'U1 (Upper lake bulk carrier)'},
  {type:'P4 (Passenger and Freight)'},
  {type:'U1 (Bulk Upper Laker)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'C2 (Canal Size Pkg. Ftr. of the North West type)'},
  {type:'U1 (Bulk Upper Laker (Turret Type))'},
  {type:'C2 (so called Western Divs. Pack. Frt.)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'M1'},
  {type:'C1 (Timber Drogher Canal Size)'},
  {type:'U1'},
  {type:'U2 (Upper Laker, Bulk)'},
  {type:'R4 (Passenger and Freight)'},
  {type:'R2 (River Pass. Stmr.)'},
  {type:'R3 (River Pass. Stmr. for Sag. Trip)'},
  {type:'U1 (Bulk Carrier)'},
  {type:'U1 (Upper Laker)'},
  {type:'U1 (Bulk Upper Laker)'},
  {type:'U2'},
  {type:'C1 (Bulk Canaller)'},
  {type:'C1 (Canal Bulk converted to Package Freighter)'},
  {type:'C1 (Canal Bulk)'},
  {type:'U1 (Upper Laker)'},
  {type:'F1'},
  {type:'R4 (Passenger and freight)'},
  {type:'R3 (Passenger Ship for St. Lawrence and Sag. R. Service)'},
  {type:'M2 (Upper Lake Self Unloader)'},
  {type:'C2 (Package Freight)'},
  {type:'M2'},
  {type:'C1 (Bulk Canaller)'},
  {type:'R4 (Passenger and Freight)'},
  {type:'C1 (Bulk Canaller)'},
  {type:'R2 (River Pass. Stmr.)'},
  {type:'B1 (First Tow Barge Canal Size then rebuilt as Canaller Bulk)'},
  {type:'T1 (Harbour Tugs Type)'},
  {type:'R3 (Pass. and Ft.)'},
  {type:'S2 (Pass. and Frt.)'},
  {type:'R4 (Passenger and Freight)'},
  {type:'R2 (Passenger)'},
  {type:'C1 (Bulk Canaller - Turret Ship Type)'},
  {type:'U1 (Upper Laker Bulk)'},
  {type:'U1 (Reduced in 1920 to C1 at Collship.)'},
  {type:'C2 (Package Freighter)'},
  {type:'U1'},
  {type:'C1 (Bulk Canaller)'},
  {type:'C5 (Passenger)'},
  {type:'S1 (Freight)'},
  {type:'U1 (Upper Laker Bulk, carried a Package Ft. Licence)'},
  {type:'C2 (Canal Size Pkg. Ftr. of the North West type)'},
  {type:'R2 (Side Wheel Pass. Stmr. for Lake of River Use)'},
  {type:'M1 (then M2 then M1)'},
  {type:'C2 (so called Western Divs. Pack. Frt.)'},
  {type:'C1 (Bulk Canaller)'},

]

carrier.length//?

// indexOf
const p1 = carrier[0].type.indexOf('(')//?

// slice - doesn't change and splice - changes

// convert str to an array
let newstr =carrier[0].type.split('')//?
// insert the backslash before the  first '(' and last ')'
newstr.splice(p1,0,'\\')//?
newstr.splice(-1,0,'\\')

// convert array back to str
let conditionedStr = newstr.join('')
conditionedStr//?

// create regExp with
const exp2 = RegExp(conditionedStr,'i')//?

carrier[0].type.match(exp2) //?
const key1 = 'type'
const result = carrier.filter((ele)=> ele[key1].match(exp2))
result.length//?
