let tmp = {}

tmp//?

tmp.url == undefined//?



const wallace ={
  Breath:"36.5000",
  'Built By':"",
  City:"YARMOUTH",
  'City Built':"GREEN COVE",
  Country:"CANADA",
  'Country Built':"Canada",
  'Country Closed':"",
  DB:"Wallace",
  'Data Source':"Fredick W. Wallace - Record of Canadian Shipping 1786 - 1920",
  'Date Built':"1874",
  'Date Closed':"",
  Depth:"21.9000",
  Id:"5",
  Length:"180.0000",
  Owner:"",
  Province:"Nova Scotia",
  'Province Build':"Nova Scotia",
  'Province Closed':"",
  'Reason Closed':"",
  'Record Id':"5",
  Remarks:"1905 JARLEN BQ.",
  Rigging:"SHIP",
  Tonnage:"1017.0000",
  Vessel:"A.F. STONEMAN",
  name:null,
  url:null,
}

const csl={
Beam:" 43",
BuildCountry:"Scotland",
Builder:" Clyde Shipbuilding and Engineering Co. Ltd.",
Category:"Fleet List",
Comments:"|1908-12 Acadian Mutual Steamship Co. Ltd.|(J.W. Norcross) Glasgow|1912-14 ,Acadian Canada Interlake Line Ltd.|(J.W. Norcross) Glasgow|1914-18 Acadian C.S.L.|T/S 11 ,miles SW by W from Trevose Head by UB 117 on September 16, 1918|SECTION C: CONSTRUCTION|,SHIPYARD: Clyde Shipbuilding and Engineering Co. Ltd.|",
DateFrom:" 1914",
DateTo:" 1918",
GrossTonnage:"2305",
HullNumber:"278",
LBP:" 246.5",
MarNum:"N/A",
MouldedDepth:" 26.5",
Name:" Acadian",
Notis:"(CaOKQ)AAD4864",
'Official Num':" 124258",
Owner:"CSL Fleet Record",
OwnerShipDate:"CSL OWNERSHIP DATES:",
SectionA:" BASIC SHIP PARTICULARS",
SectionB:"OWNERSHIP/NAME CHANGES/DISPOSAL",
ShipyardLocation:" Port Glasgow",
Tonnage:"1457",
Type:" C1 (Canal Sized Bulk Carrier)",
YearBuilt:"1908",
atRpm:"",
boilerBuilder:"Clyde Shipbuilding and Engineering Co. Ltd.",
boilerType:": Cyl S.E.|",
bowThruster:"Nil",
chronology:"CHRONOLOGY:",
cylinders:"3 (18x30x50)",
dateOfDelivery:"1908",
dateOfLaunch:"",
engineBuilder:"Clyde Shipbuilding and Engineering Co. Ltd.",
engineSize:"13x10",
engineType:"SR (T.E.)",
hullType:": Steel",
numberOfBoilers:"2",
placeEngineBuilt:"t Glasgow, Scotland",
sectionE:"ENGINE AND MECHANICAL",
sternThruster:"Nil",
stroke:"36",
superstructure:"Steel",
turbines:"Not Applicable",
vesselOtherName:"",
yearEngineBuilt:"1908",
}

const snyders={
'Article Num':"3",
'Article Title':"CANADA'S NO. 1",
Captain:"",
Event:"",
Illustrations:"",
Index:"3/CANADA'S NO. 1/Stuart Schooner/Scow/COLLINGWOOD/",
People:"",
Place:"COLLINGWOOD",
'Ship Name':"Stuart Schooner",
'Ship Type':"Scow",
'When Built':"",
'Where Built':"",
}

const registry ={
  Beam:"",
  'Built At':", , ",
  'Built By':"",
  'Data Built':"",
  'Date Built':"",
  'Date Registered':"",
  'Date Registration Closed':"1881/02/24",
  'Date of Reason Closed':"",
  Deck:"ONE",
  Depth:"",
  Frame:"",
  Gallery:"",
  Gross:"",
  HorsePower:"",
  Id:"3259",
  Length:"",
  Location:"MONTREAL, QUEBEC, CANADA",
  Name:"A",
  Net:"",
  'Number of Engines':"",
  'Number of Masts':"ONE",
  'Official Number':"",
  'Place Closed':", , ",
  Propulsion:"",
  'Reason Closed':"BROKEN UP",
  Registration:"1/1864",
  'Source of Data':"N.A.C., RG-42, C-2467, VOL. 214",
  Stern:"ROUND",
  Type:"CARVEL",
  'Type of Engine':"",
  'Type of Rig':"SLOOP",
  'Unit Horse Power':"",
}

const mills ={
Addendum:"A. D. Cross;  49x16x9 Owned by D. Armstrong, Port Colborne 1898, Mrs. I.M. Armstrong, Port Colborne 1901, Canadian Dredging Co., Midland, Ont. 1917; J.J. Harrigan, Port Dalhousie 1921. Built as a Welland Canal tug.",
BuiltDate:"1897",
CountryRegAfterCanada:null,
DB:"Mills",
Date1:"1897",
Date2:"1922",
Date3:null,
Date4:null,
Date5:null,
Date6:null,
Date7:null,
DateClosed:null,
DateClosedEvent:null,
DateFirstCdnReg:null,
Dimensions:"[ 49 x 16 - 47 tons ]",
EntryDate:"08/04/2003 10:46:32",
MillsNum:"000030",
Name2:"Austin H.",
Name3:null,
Name4:null,
Name5:null,
Name6:null,
Name7:null,
NamePreReg:null,
NextCountryRegAfterCanada:null,
NextDateRegisteredAfterCanada:null,
OfficialNum:"97014",
PlaceClosed:", , ",
PreReg:null,
Propulsion:"Screw Propeller",
ReasonClosed:"",
RecordId:"000030",
RegId:null,
Remarks:"",
Vessel:"A.D. Cross",
WhereBuilt:"Pt. Colborne, Ontario, Canada ",
}

let cart = []

cart.push(mills)
cart.push(csl)
cart.push(registry)
cart.push(snyders)
cart.push(wallace)

cart//?
